services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: svmucm
    ports:
      - 3307:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 20s
      retries: 7
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: svmucm-server
    depends_on:
      mysql:
        condition: service_healthy
    links:
      - mysql
    ports:
      - 3000:3000
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: svmucm-client
    ports:
      - 4200:4200